# Generated by Django 4.2.7 on 2025-11-13 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('asset_code', models.CharField(max_length=50, unique=True, verbose_name='Código de Activo')),
                ('vehicle_type', models.CharField(choices=[('CAMION_SUPERSUCKER', 'Camión Supersucker'), ('CAMIONETA_MDO', 'Camioneta MDO'), ('RETROEXCAVADORA_MDO', 'Retroexcavadora MDO'), ('CARGADOR_FRONTAL_MDO', 'Cargador Frontal MDO'), ('MINICARGADOR_MDO', 'Minicargador MDO')], max_length=50, verbose_name='Tipo de Vehículo')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Fabricante')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Patente')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Instalación')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Última Mantención')),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operativo'), ('DOWN', 'Fuera de Servicio'), ('MAINTENANCE', 'En Mantenimiento'), ('RETIRED', 'Retirado')], default='OPERATIONAL', max_length=20, verbose_name='Estado')),
                ('criticality', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20, verbose_name='Criticidad')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='Especificaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activo/Vehículo',
                'verbose_name_plural': 'Activos/Vehículos',
                'db_table': 'assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('MANUAL', 'Manual'), ('PHOTO', 'Fotografía'), ('CERTIFICATE', 'Certificado'), ('DRAWING', 'Plano'), ('OTHER', 'Otro')], max_length=50, verbose_name='Tipo de Documento')),
                ('file_url', models.URLField(verbose_name='URL del Archivo')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('file_size', models.IntegerField(verbose_name='Tamaño (bytes)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assets.asset', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Documento de Activo',
                'verbose_name_plural': 'Documentos de Activos',
                'db_table': 'asset_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
