# Generated by Django 4.2.7 on 2025-11-13 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_orders', '0001_initial'),
        ('assets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Parte')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('minimum_stock', models.IntegerField(default=0, verbose_name='Stock Mínimo')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario')),
                ('location', models.CharField(max_length=100, verbose_name='Ubicación en Bodega')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compatible_assets', models.ManyToManyField(blank=True, related_name='compatible_spare_parts', to='assets.asset', verbose_name='Activos Compatibles')),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'db_table': 'spare_parts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('ADJUSTMENT', 'Ajuste')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('stock_before', models.IntegerField(verbose_name='Stock Anterior')),
                ('stock_after', models.IntegerField(verbose_name='Stock Posterior')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.sparepart', verbose_name='Repuesto')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='work_orders.workorder', verbose_name='Orden de Trabajo')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['spare_part', '-created_at'], name='stock_movem_spare_p_638f64_idx'), models.Index(fields=['work_order'], name='stock_movem_work_or_a123d2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['part_number'], name='spare_parts_part_nu_98a1ed_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['category'], name='spare_parts_categor_e0472e_idx'),
        ),
    ]
