# Cloud Build configuration for user migration job
steps:
  # Build the migration job image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/migrate-users-firebase'
      - '-f'
      - 'Dockerfile.migrate'
      - '.'
    dir: 'backend'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/migrate-users-firebase'

  # Create/Update Cloud Run Job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'create'
      - 'migrate-users-firebase'
      - '--image=gcr.io/$PROJECT_ID/migrate-users-firebase'
      - '--region=us-central1'
      - '--set-secrets=FIREBASE_CREDENTIALS_PATH=firebase-credentials:latest'
      - '--set-secrets=DATABASE_URL=database-url:latest'
      - '--set-env-vars=DJANGO_SETTINGS_MODULE=config.settings.production'
      - '--set-env-vars=FIREBASE_DATABASE_URL=https://cmms-somacor-prod.firebaseio.com'
      - '--set-env-vars=FIREBASE_STORAGE_BUCKET=cmms-somacor-prod.appspot.com'
      - '--add-cloudsql-instances=argon-edge-478500-i8:us-central1:cmms-db'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--max-retries=3'
      - '--task-timeout=30m'

images:
  - 'gcr.io/$PROJECT_ID/migrate-users-firebase'

options:
  logging: CLOUD_LOGGING_ONLY
