# Generated by Django 4.2.7 on 2025-11-20 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_location_city_location_coordinates_location_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Anterior')),
                ('new_status', models.CharField(max_length=50, verbose_name='Nuevo Estado')),
                ('previous_odometer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_odometer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='assets.asset')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'db_table': 'asset_status_history',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['asset', '-changed_at'], name='asset_statu_asset_i_a6c06e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_type', models.CharField(choices=[('OPERANDO', 'Operando'), ('DETENIDA', 'Detenida'), ('EN_MANTENIMIENTO', 'En Mantenimiento'), ('FUERA_DE_SERVICIO', 'Fuera de Servicio')], max_length=50, verbose_name='Tipo de Estado')),
                ('odometer_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lectura Odómetro/Horómetro')),
                ('fuel_level', models.IntegerField(blank=True, help_text='Porcentaje de 0 a 100', null=True, verbose_name='Nivel de Combustible (%)')),
                ('condition_notes', models.TextField(blank=True, null=True, verbose_name='Notas de Condición')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='assets.asset')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_status_updates', to='assets.location')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de Activo',
                'verbose_name_plural': 'Estados de Activos',
                'db_table': 'asset_status',
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['asset', '-reported_at'], name='asset_statu_asset_i_a8ad88_idx'), models.Index(fields=['status_type'], name='asset_statu_status__9e12d4_idx'), models.Index(fields=['reported_by'], name='asset_statu_reporte_8176cf_idx')],
            },
        ),
    ]
