# Generated by Django 4.2.7 on 2025-11-24 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_create_initial_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_chat_id',
        ),
    ]
