# Generated by Django 4.2.7 on 2025-11-13 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('plan_type', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('PREDICTIVE', 'Predictivo')], max_length=20)),
                ('recurrence_type', models.CharField(choices=[('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual'), ('CUSTOM', 'Personalizado')], max_length=20)),
                ('recurrence_interval', models.IntegerField(default=1)),
                ('next_due_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('estimated_duration', models.IntegerField(help_text='Duración estimada en minutos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='assets.asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_maintenance_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de Mantenimiento',
                'verbose_name_plural': 'Planes de Mantenimiento',
                'db_table': 'maintenance_plans',
                'ordering': ['next_due_date'],
            },
        ),
    ]
