# Generated by Django 4.2.7 on 2025-11-25 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0003_location_city_location_coordinates_location_region_and_more'),
        ('checklists', '0001_initial'),
        ('work_orders', '0002_make_asset_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_url', models.URLField(verbose_name='URL Original')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='URL Miniatura')),
                ('file_size', models.IntegerField(verbose_name='Tamaño (bytes)')),
                ('width', models.IntegerField(verbose_name='Ancho')),
                ('height', models.IntegerField(verbose_name='Alto')),
                ('format', models.CharField(max_length=10, verbose_name='Formato')),
                ('captured_at', models.DateTimeField(verbose_name='Fecha de Captura')),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud GPS')),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud GPS')),
                ('gps_altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Altitud GPS (m)')),
                ('compass_heading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Orientación (grados)')),
                ('device_info', models.JSONField(blank=True, default=dict, verbose_name='Info del Dispositivo')),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20, verbose_name='Estado de Procesamiento')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('processing_error', models.TextField(blank=True, verbose_name='Error de Procesamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_photos', to='assets.asset', verbose_name='Activo')),
                ('checklist_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='checklists.checklistresponse', verbose_name='Checklist')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='work_orders.workorder', verbose_name='Orden de Trabajo')),
            ],
            options={
                'verbose_name': 'Foto de Inspección',
                'verbose_name_plural': 'Fotos de Inspección',
                'db_table': 'inspection_photos',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('labels', models.JSONField(blank=True, default=list, verbose_name='Etiquetas Detectadas')),
                ('detected_objects', models.JSONField(blank=True, default=list, verbose_name='Objetos Localizados')),
                ('text_annotations', models.JSONField(blank=True, default=list, verbose_name='Texto Detectado (OCR)')),
                ('dominant_colors', models.JSONField(blank=True, default=list, verbose_name='Colores Dominantes')),
                ('safe_search', models.JSONField(blank=True, default=dict, verbose_name='Safe Search')),
                ('anomalies_detected', models.BooleanField(default=False, verbose_name='Anomalías Detectadas')),
                ('anomaly_confidence', models.FloatField(blank=True, null=True, verbose_name='Confianza de Anomalía')),
                ('damage_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Daño')),
                ('damage_severity', models.CharField(blank=True, max_length=20, verbose_name='Severidad del Daño')),
                ('damage_confidence', models.FloatField(blank=True, null=True, verbose_name='Confianza de Daño')),
                ('processing_time_ms', models.IntegerField(verbose_name='Tiempo de Procesamiento (ms)')),
                ('model_version', models.CharField(max_length=50, verbose_name='Versión del Modelo')),
                ('vision_ai_used', models.BooleanField(default=True, verbose_name='Vision AI Usado')),
                ('cached_result', models.BooleanField(default=False, verbose_name='Resultado en Caché')),
                ('cache_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Caché Expira')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='images.inspectionphoto', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Resultado de Análisis',
                'verbose_name_plural': 'Resultados de Análisis',
                'db_table': 'image_analysis_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('damage_type', models.CharField(choices=[('CORROSION', 'Corrosión'), ('MECHANICAL_WEAR', 'Desgaste Mecánico'), ('ELECTRICAL_FAILURE', 'Falla Eléctrica'), ('HYDRAULIC_LEAK', 'Fuga Hidráulica'), ('STRUCTURAL_CRACK', 'Grieta Estructural'), ('THERMAL_DAMAGE', 'Daño Térmico')], max_length=50, verbose_name='Tipo de Daño')),
                ('severity', models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto'), ('CRITICAL', 'Crítico')], max_length=20, verbose_name='Severidad')),
                ('confidence', models.FloatField(verbose_name='Confianza')),
                ('auto_generated_description', models.TextField(verbose_name='Descripción Auto-generada')),
                ('user_notes', models.TextField(blank=True, verbose_name='Notas del Usuario')),
                ('maintenance_recommendation', models.TextField(blank=True, verbose_name='Recomendación de Mantenimiento')),
                ('maintenance_plan_updated', models.BooleanField(default=False, verbose_name='Plan de Mantenimiento Actualizado')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('IN_PROGRESS', 'En Progreso'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20, verbose_name='Estado')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='assets.asset', verbose_name='Activo')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='images.inspectionphoto', verbose_name='Foto')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_damage_reports', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports', to='work_orders.workorder', verbose_name='Orden de Trabajo')),
            ],
            options={
                'verbose_name': 'Reporte de Daño',
                'verbose_name_plural': 'Reportes de Daño',
                'db_table': 'damage_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisualAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(choices=[('CORROSION', 'Corrosión'), ('CRACK', 'Grieta'), ('LEAK', 'Fuga'), ('WEAR', 'Desgaste'), ('DEFORMATION', 'Deformación'), ('OTHER', 'Otro')], max_length=50, verbose_name='Tipo de Anomalía')),
                ('severity', models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto'), ('CRITICAL', 'Crítico')], max_length=20, verbose_name='Severidad')),
                ('confidence', models.FloatField(verbose_name='Confianza')),
                ('bounding_box', models.JSONField(verbose_name='Caja Delimitadora')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('confirmed_by_user', models.BooleanField(blank=True, null=True, verbose_name='Confirmado por Usuario')),
                ('user_feedback', models.TextField(blank=True, verbose_name='Feedback del Usuario')),
                ('feedback_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Feedback')),
                ('alert_sent', models.BooleanField(default=False, verbose_name='Alerta Enviada')),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Alerta Enviada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='images.imageanalysisresult', verbose_name='Resultado de Análisis')),
                ('feedback_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Feedback por')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='images.inspectionphoto', verbose_name='Foto')),
                ('work_order_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='work_orders.workorder', verbose_name='Orden de Trabajo Creada')),
            ],
            options={
                'verbose_name': 'Anomalía Visual',
                'verbose_name_plural': 'Anomalías Visuales',
                'db_table': 'visual_anomalies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['photo'], name='visual_anom_photo_i_8ef5c3_idx'), models.Index(fields=['anomaly_type'], name='visual_anom_anomaly_1b1dde_idx'), models.Index(fields=['severity'], name='visual_anom_severit_f31c05_idx'), models.Index(fields=['confirmed_by_user'], name='visual_anom_confirm_e093ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reading_type', models.CharField(choices=[('ODOMETER', 'Odómetro'), ('HOUR_METER', 'Horómetro'), ('PRESSURE', 'Presión'), ('TEMPERATURE', 'Temperatura'), ('FUEL_LEVEL', 'Nivel de Combustible'), ('OTHER', 'Otro')], max_length=50, verbose_name='Tipo de Lectura')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('unit', models.CharField(max_length=20, verbose_name='Unidad')),
                ('confidence', models.FloatField(verbose_name='Confianza OCR')),
                ('text_detected', models.CharField(max_length=100, verbose_name='Texto Detectado')),
                ('bounding_box', models.JSONField(verbose_name='Caja Delimitadora')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Es Válido')),
                ('is_outlier', models.BooleanField(default=False, verbose_name='Es Valor Atípico')),
                ('validation_notes', models.TextField(blank=True, verbose_name='Notas de Validación')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Validación')),
                ('previous_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lectura Anterior')),
                ('expected_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rango Esperado Mínimo')),
                ('expected_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rango Esperado Máximo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='assets.asset', verbose_name='Activo')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='images.inspectionphoto', verbose_name='Foto')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_readings', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Lectura de Medidor',
                'verbose_name_plural': 'Lecturas de Medidores',
                'db_table': 'meter_readings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asset', '-created_at'], name='meter_readi_asset_i_8d3190_idx'), models.Index(fields=['reading_type'], name='meter_readi_reading_528e9f_idx'), models.Index(fields=['is_outlier'], name='meter_readi_is_outl_b2af9c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inspectionphoto',
            index=models.Index(fields=['asset', '-captured_at'], name='inspection__asset_i_e98c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionphoto',
            index=models.Index(fields=['work_order'], name='inspection__work_or_9775ce_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionphoto',
            index=models.Index(fields=['checklist_response'], name='inspection__checkli_7bd90b_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionphoto',
            index=models.Index(fields=['processing_status'], name='inspection__process_1ee65c_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionphoto',
            index=models.Index(fields=['uploaded_by'], name='inspection__uploade_41ed70_idx'),
        ),
        migrations.AddIndex(
            model_name='imageanalysisresult',
            index=models.Index(fields=['photo'], name='image_analy_photo_i_6a9ae9_idx'),
        ),
        migrations.AddIndex(
            model_name='imageanalysisresult',
            index=models.Index(fields=['anomalies_detected'], name='image_analy_anomali_d9e26f_idx'),
        ),
        migrations.AddIndex(
            model_name='imageanalysisresult',
            index=models.Index(fields=['damage_type'], name='image_analy_damage__b5421b_idx'),
        ),
        migrations.AddIndex(
            model_name='damagereport',
            index=models.Index(fields=['asset', '-created_at'], name='damage_repo_asset_i_f74cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='damagereport',
            index=models.Index(fields=['damage_type'], name='damage_repo_damage__b13acc_idx'),
        ),
        migrations.AddIndex(
            model_name='damagereport',
            index=models.Index(fields=['severity'], name='damage_repo_severit_04c1b5_idx'),
        ),
        migrations.AddIndex(
            model_name='damagereport',
            index=models.Index(fields=['status'], name='damage_repo_status_539828_idx'),
        ),
    ]
