# Generated by Django 4.2.7 on 2025-11-13 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_orders', '0001_initial'),
        ('assets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('vehicle_type', models.CharField(max_length=50, verbose_name='Tipo de Vehículo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('items', models.JSONField(default=list, verbose_name='Items del Checklist')),
                ('is_system_template', models.BooleanField(default=False, verbose_name='Plantilla del Sistema')),
                ('passing_score', models.IntegerField(default=80, verbose_name='Puntaje Mínimo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Checklist',
                'verbose_name_plural': 'Plantillas de Checklist',
                'db_table': 'checklist_templates',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('responses', models.JSONField(default=list, verbose_name='Respuestas')),
                ('score', models.IntegerField(verbose_name='Puntaje')),
                ('passed', models.BooleanField(verbose_name='Aprobado')),
                ('pdf_url', models.URLField(blank=True, null=True, verbose_name='URL del PDF')),
                ('signature_url', models.URLField(blank=True, null=True, verbose_name='URL de Firma')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Completado')),
                ('operator_name', models.CharField(max_length=200, verbose_name='Nombre del Operador')),
                ('shift', models.CharField(blank=True, max_length=50, verbose_name='Turno')),
                ('odometer_reading', models.IntegerField(blank=True, null=True, verbose_name='Kilometraje/Horómetro')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_responses', to='assets.asset', verbose_name='Activo')),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completed_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Completado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='checklists.checklisttemplate', verbose_name='Plantilla')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='work_orders.workorder', verbose_name='Orden de Trabajo')),
            ],
            options={
                'verbose_name': 'Checklist Completado',
                'verbose_name_plural': 'Checklists Completados',
                'db_table': 'checklist_responses',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['asset', '-completed_at'], name='checklist_r_asset_i_545d82_idx'), models.Index(fields=['work_order'], name='checklist_r_work_or_e4553e_idx'), models.Index(fields=['completed_by'], name='checklist_r_complet_96b6b6_idx')],
            },
        ),
    ]
